#!/bin/sh

# Get current branch name
branch_name=$(git rev-parse --abbrev-ref HEAD)

if  [[ "$branch_name" == dev-* ]]; then
    exit 0
else
    echo "============================================================"
    echo "ERROR: Commits on branch '$branch_name' are not allowed!"
    echo "Branch names must start with 'dev-' (e.g., dev-cool-new-feature)"
    echo "Commit aborted."
    echo "============================================================"
    exit 1
fi
