#pragma once

#ifndef SHINKIRO_PLATFORM_GL_H
#    define SHINKIRO_PLATFORM_GL_H

#    include <Platform/_Defs.h>

#    include <glad/glad.h>
#    include <glfw/glfw3.h>

namespace Shinkiro::Platform::OpenGL
{
#    define DECLARE_GL_FUNC( type, name ) extern PLATFORM_API type name;

    PLATFORM_API bool Initialize( GLFWwindow * window );

    DECLARE_GL_FUNC( PFNGLCREATESHADERPROC, glCreateShader )
    DECLARE_GL_FUNC( PFNGLDELETESHADERPROC, glDeleteShader )
    DECLARE_GL_FUNC( PFNGLSHADERSOURCEPROC, glShaderSource )
    DECLARE_GL_FUNC( PFNGLCOMPILESHADERPROC, glCompileShader )
    DECLARE_GL_FUNC( PFNGLGETSHADERIVPROC, glGetShaderiv )
    DECLARE_GL_FUNC( PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog )
    DECLARE_GL_FUNC( PFNGLCREATEPROGRAMPROC, glCreateProgram )
    DECLARE_GL_FUNC( PFNGLDELETEPROGRAMPROC, glDeleteProgram )
    DECLARE_GL_FUNC( PFNGLATTACHSHADERPROC, glAttachShader )
    DECLARE_GL_FUNC( PFNGLLINKPROGRAMPROC, glLinkProgram )
    DECLARE_GL_FUNC( PFNGLUSEPROGRAMPROC, glUseProgram )
    DECLARE_GL_FUNC( PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation )
    DECLARE_GL_FUNC( PFNGLUNIFORM1IPROC, glUniform1i )
    DECLARE_GL_FUNC( PFNGLUNIFORM2FVPROC, glUniform2fv )
    DECLARE_GL_FUNC( PFNGLUNIFORM3FVPROC, glUniform3fv )
    DECLARE_GL_FUNC( PFNGLUNIFORM4FVPROC, glUniform4fv )
    DECLARE_GL_FUNC( PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv )
    DECLARE_GL_FUNC( PFNGLGENBUFFERSPROC, glGenBuffers )
    DECLARE_GL_FUNC( PFNGLDELETEBUFFERSPROC, glDeleteBuffers )
    DECLARE_GL_FUNC( PFNGLBINDBUFFERPROC, glBindBuffer )
    DECLARE_GL_FUNC( PFNGLBUFFERDATAPROC, glBufferData )
    DECLARE_GL_FUNC( PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray )
    DECLARE_GL_FUNC( PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer )
    DECLARE_GL_FUNC( PFNGLGENTEXTURESPROC, glGenTextures )
    DECLARE_GL_FUNC( PFNGLDELETETEXTURESPROC, glDeleteTextures )
    DECLARE_GL_FUNC( PFNGLBINDTEXTUREPROC, glBindTexture )
    DECLARE_GL_FUNC( PFNGLTEXPARAMETERIPROC, glTexParameteri )
    DECLARE_GL_FUNC( PFNGLACTIVETEXTUREPROC, glActiveTexture )
    DECLARE_GL_FUNC( PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays )
    DECLARE_GL_FUNC( PFNGLBINDVERTEXARRAYPROC, glBindVertexArray )
    DECLARE_GL_FUNC( PFNGLDELETEVERTEXARRAYSPROC, glDeleteVertexArrays )
    DECLARE_GL_FUNC( PFNGLDRAWARRAYSPROC, glDrawArrays )
    DECLARE_GL_FUNC( PFNGLDRAWELEMENTSPROC, glDrawElements )
    DECLARE_GL_FUNC( PFNGLDEPTHFUNCPROC, glDepthFunc )
    DECLARE_GL_FUNC( PFNGLDEPTHMASKPROC, glDepthMask )
    DECLARE_GL_FUNC( PFNGLENABLEPROC, glEnable )
    DECLARE_GL_FUNC( PFNGLDISABLEPROC, glDisable )
    DECLARE_GL_FUNC( PFNGLBLENDFUNCPROC, glBlendFunc )
    DECLARE_GL_FUNC( PFNGLGETBOOLEANVPROC, glGetBooleanv )
    DECLARE_GL_FUNC( PFNGLISENABLEDPROC, glIsEnabled )
    DECLARE_GL_FUNC( PFNGLGETPROGRAMIVPROC, glGetProgramiv )
    DECLARE_GL_FUNC( PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog )
    DECLARE_GL_FUNC( PFNGLTEXIMAGE2DPROC, glTexImage2D )
    DECLARE_GL_FUNC( PFNGLGENERATEMIPMAPPROC, glGenerateMipmap )
    DECLARE_GL_FUNC( PFNGLCLEARCOLORPROC, glClearColor )
    DECLARE_GL_FUNC( PFNGLCLEARPROC, glClear )
    DECLARE_GL_FUNC( PFNGLUNIFORM1FPROC, glUniform1f )
    DECLARE_GL_FUNC( PFNGLUNIFORMMATRIX2FVPROC, glUniformMatrix2fv )
    DECLARE_GL_FUNC( PFNGLUNIFORMMATRIX3FVPROC, glUniformMatrix3fv )
    DECLARE_GL_FUNC( PFNGLVIEWPORTPROC, glViewport )
}

#endif
